version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - API_KEY=${API_KEY}
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./account_service_credentials.json:/etc/secrets/account_service_credentials.json:ro
    restart: unless-stopped 